package modelo;

// Generated 09/01/2012 10:28:45 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentoPersonalId generated by hbm2java
 */
@Embeddable
public class DocumentoPersonalId implements java.io.Serializable {

	private String cedulaRif;
	private int codigoDocumentoEntregado;

	public DocumentoPersonalId() {
	}

	public DocumentoPersonalId(String cedulaRif, int codigoDocumentoEntregado) {
		this.cedulaRif = cedulaRif;
		this.codigoDocumentoEntregado = codigoDocumentoEntregado;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "codigo_documento_entregado", nullable = false)
	public int getCodigoDocumentoEntregado() {
		return this.codigoDocumentoEntregado;
	}

	public void setCodigoDocumentoEntregado(int codigoDocumentoEntregado) {
		this.codigoDocumentoEntregado = codigoDocumentoEntregado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentoPersonalId))
			return false;
		DocumentoPersonalId castOther = (DocumentoPersonalId) other;

		return ((this.getCedulaRif() == castOther.getCedulaRif()) || (this
				.getCedulaRif() != null && castOther.getCedulaRif() != null && this
				.getCedulaRif().equals(castOther.getCedulaRif())))
				&& (this.getCodigoDocumentoEntregado() == castOther
						.getCodigoDocumentoEntregado());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCedulaRif() == null ? 0 : this.getCedulaRif().hashCode());
		result = 37 * result + this.getCodigoDocumentoEntregado();
		return result;
	}

}
